# Generated by Django 5.2 on 2025-07-27 19:58

import data_control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=data_control.models.upload_image, verbose_name='About image')),
                ('description', models.TextField(help_text='Add a description about you', verbose_name='About you')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(help_text='Upload a image (max 1920x1055px, max 2MB)', upload_to=data_control.models.upload_image, verbose_name='Home image')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=data_control.models.upload_image, verbose_name='Enter the product image')),
                ('product_name', models.CharField()),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=data_control.models.upload_image, verbose_name='Enter the project image')),
                ('project_name', models.CharField()),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('external_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a square image (max 500x500px, max 1MB)', upload_to=data_control.models.upload_image, verbose_name='Profile Picture')),
                ('name', models.CharField(help_text='Full name of the person giving the testimonial', max_length=50, verbose_name='Client Name')),
                ('field', models.CharField(help_text='Example: Freelancer, UX Designer, CEO...', max_length=255, verbose_name='Occupation or Role')),
                ('text', models.CharField(help_text='The actual testimonial message (minimum 10 characters)', max_length=255, verbose_name='Testimonial Text')),
            ],
        ),
    ]
