# Generated by Django 5.2 on 2025-07-27 22:50

import data_control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(help_text='Write something about you', verbose_name='About Description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(help_text='Max 1920x1055px', upload_to=data_control.models.upload_image, verbose_name='About Image'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='background_image',
            field=models.ImageField(help_text='Max size 2MB, max dimensions 1920x1055px', upload_to=data_control.models.upload_image, verbose_name='Home Background Image'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(help_text='Minimum 255 characters', verbose_name='Product Details'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(help_text='Minimum 100 characters', max_length=255, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=data_control.models.upload_image, verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(help_text='Minimum 255 characters', verbose_name='Project Details'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(help_text='Minimum 100 characters', max_length=255, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='external_link',
            field=models.URLField(help_text='Link to the live project', verbose_name='External URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to=data_control.models.upload_image, verbose_name='Project Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.TextField(help_text='Minimum 255 characters', verbose_name='Detailed Content'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(help_text='Minimum 100 characters', max_length=255, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(help_text='Enter the name of the service', max_length=100, verbose_name='Service Name'),
        ),
    ]
